// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import XCTest
@testable import SwiftUnits

final class BitsTests: XCTestCase {
	func testConvertKnownBitsToKilobits_1() throws {
		let result = DataStorage.Bits.toKilobits(100.0)
		XCTAssertEqual(0.1, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToKilobits_2() throws {
		let result = DataStorage.Bits.toKilobits(6021.0)
		XCTAssertEqual(6.021, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToKilobits_3() throws {
		let result = DataStorage.Bits.toKilobits(9100.0)
		XCTAssertEqual(9.1, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMegabits_1() throws {
		let result = DataStorage.Bits.toMegabits(9000000.0)
		XCTAssertEqual(9.0, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMegabits_2() throws {
		let result = DataStorage.Bits.toMegabits(123456.0)
		XCTAssertEqual(0.123456, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMegabits_3() throws {
		let result = DataStorage.Bits.toMegabits(1900000.0)
		XCTAssertEqual(1.9, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToGigabits_1() throws {
		let result = DataStorage.Bits.toGigabits(190000000.0)
		XCTAssertEqual(0.19, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToGigabits_2() throws {
		let result = DataStorage.Bits.toGigabits(8009.0)
		XCTAssertEqual(8.009e-6, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToGigabits_3() throws {
		let result = DataStorage.Bits.toGigabits(987654321.0)
		XCTAssertEqual(0.987654321, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToTerabits_1() throws {
		let result = DataStorage.Bits.toTerabits(987654321234.0)
		XCTAssertEqual(0.987654321234, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToTerabits_2() throws {
		let result = DataStorage.Bits.toTerabits(1234567890123456.0)
		XCTAssertEqual(1234.567890123455982, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToTerabits_3() throws {
		let result = DataStorage.Bits.toTerabits(999888777666555.0)
		XCTAssertEqual(999.888777666555029, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToKilobytes_1() throws {
		let result = DataStorage.Bits.toKilobytes(900.0)
		XCTAssertEqual(0.1125, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToKilobytes_2() throws {
		let result = DataStorage.Bits.toKilobytes(12345.0)
		XCTAssertEqual(1.543125, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToKilobytes_3() throws {
		let result = DataStorage.Bits.toKilobytes(6000.9)
		XCTAssertEqual(0.7501125, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMegabytes_1() throws {
		let result = DataStorage.Bits.toMegabytes(123456.0)
		XCTAssertEqual(0.015432, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMegabytes_2() throws {
		let result = DataStorage.Bits.toMegabytes(900800.0)
		XCTAssertEqual(0.1126, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMegabytes_3() throws {
		let result = DataStorage.Bits.toMegabytes(999888777.0)
		XCTAssertEqual(124.986097125, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToGigabytes_1() throws {
		let result = DataStorage.Bits.toGigabytes(999888777.0)
		XCTAssertEqual(0.124986097125, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToGigabytes_2() throws {
		let result = DataStorage.Bits.toGigabytes(1.9e+9)
		XCTAssertEqual(0.2375, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToGigabytes_3() throws {
		let result = DataStorage.Bits.toGigabytes(80090077.0)
		XCTAssertEqual(0.010011259625, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToTerabytes_1() throws {
		let result = DataStorage.Bits.toTerabytes(999888777666.0)
		XCTAssertEqual(0.12498609720825, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToTerabytes_2() throws {
		let result = DataStorage.Bits.toTerabytes(12345678912345.0)
		XCTAssertEqual(1.5432098640431251, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToTerabytes_3() throws {
		let result = DataStorage.Bits.toTerabytes(111999222888333.0)
		XCTAssertEqual(13.9999028610416243, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToKibibits_1() throws {
		let result = DataStorage.Bits.toKibibits(1800.0)
		XCTAssertEqual(1.757813, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToKibibits_2() throws {
		let result = DataStorage.Bits.toKibibits(888.0)
		XCTAssertEqual(0.867188, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToKibibits_3() throws {
		let result = DataStorage.Bits.toKibibits(7687.0)
		XCTAssertEqual(7.506836, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMebibits_1() throws {
		let result = DataStorage.Bits.toMebibits(999888.0)
		XCTAssertEqual(0.953567505, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMebibits_2() throws {
		let result = DataStorage.Bits.toMebibits(1234567.0)
		XCTAssertEqual(1.17737484, result, accuracy: 0.01)
	}

	func testConvertKnownBitsToMebibits_3() throws {
		let result = DataStorage.Bits.toMebibits(900800.0)
		XCTAssertEqual(0.859069824, result, accuracy: 0.01)
	}

}

final class GigabitsTests: XCTestCase {
	func testConvertKnownGigabitsToBits_1() throws {
		let result = DataStorage.Gigabits.toBits(0.0009)
		XCTAssertEqual(900000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToBits_2() throws {
		let result = DataStorage.Gigabits.toBits(0.00007)
		XCTAssertEqual(70000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToBits_3() throws {
		let result = DataStorage.Gigabits.toBits(1.2e-5)
		XCTAssertEqual(12000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKilobits_1() throws {
		let result = DataStorage.Gigabits.toKilobits(0.01)
		XCTAssertEqual(10000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKilobits_2() throws {
		let result = DataStorage.Gigabits.toKilobits(0.91)
		XCTAssertEqual(910000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKilobits_3() throws {
		let result = DataStorage.Gigabits.toKilobits(6.1)
		XCTAssertEqual(6.1e+6, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMegabits_1() throws {
		let result = DataStorage.Gigabits.toMegabits(6.1)
		XCTAssertEqual(6100.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMegabits_2() throws {
		let result = DataStorage.Gigabits.toMegabits(0.961)
		XCTAssertEqual(961.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMegabits_3() throws {
		let result = DataStorage.Gigabits.toMegabits(1.2e-3)
		XCTAssertEqual(1.2, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToTerabits_1() throws {
		let result = DataStorage.Gigabits.toTerabits(1200.0)
		XCTAssertEqual(1.2, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToTerabits_2() throws {
		let result = DataStorage.Gigabits.toTerabits(90012.0)
		XCTAssertEqual(90.012, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToTerabits_3() throws {
		let result = DataStorage.Gigabits.toTerabits(8000.0)
		XCTAssertEqual(8.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKilobytes_1() throws {
		let result = DataStorage.Gigabits.toKilobytes(1.2)
		XCTAssertEqual(150000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKilobytes_2() throws {
		let result = DataStorage.Gigabits.toKilobytes(0.9)
		XCTAssertEqual(112500.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKilobytes_3() throws {
		let result = DataStorage.Gigabits.toKilobytes(0.001)
		XCTAssertEqual(125.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMegabytes_1() throws {
		let result = DataStorage.Gigabits.toMegabytes(0.9)
		XCTAssertEqual(112.5, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMegabytes_2() throws {
		let result = DataStorage.Gigabits.toMegabytes(1.2)
		XCTAssertEqual(150.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMegabytes_3() throws {
		let result = DataStorage.Gigabits.toMegabytes(80.1)
		XCTAssertEqual(10012.5, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToGigabytes_1() throws {
		let result = DataStorage.Gigabits.toGigabytes(99.0)
		XCTAssertEqual(12.375, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToGigabytes_2() throws {
		let result = DataStorage.Gigabits.toGigabytes(123.123)
		XCTAssertEqual(15.390375, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToGigabytes_3() throws {
		let result = DataStorage.Gigabits.toGigabytes(8000.9)
		XCTAssertEqual(1000.1125, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToTerabytes_1() throws {
		let result = DataStorage.Gigabits.toTerabytes(9000.0)
		XCTAssertEqual(1.125, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToTerabytes_2() throws {
		let result = DataStorage.Gigabits.toTerabytes(1234567.0)
		XCTAssertEqual(154.320875, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToTerabytes_3() throws {
		let result = DataStorage.Gigabits.toTerabytes(613.0)
		XCTAssertEqual(0.076625, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKibibits_1() throws {
		let result = DataStorage.Gigabits.toKibibits(0.8)
		XCTAssertEqual(781250.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKibibits_2() throws {
		let result = DataStorage.Gigabits.toKibibits(0.012)
		XCTAssertEqual(11718.75, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToKibibits_3() throws {
		let result = DataStorage.Gigabits.toKibibits(0.002)
		XCTAssertEqual(1953.125, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMebibits_1() throws {
		let result = DataStorage.Gigabits.toMebibits(0.002)
		XCTAssertEqual(1.9073486, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMebibits_2() throws {
		let result = DataStorage.Gigabits.toMebibits(0.9)
		XCTAssertEqual(858.30688476562, result, accuracy: 0.01)
	}

	func testConvertKnownGigabitsToMebibits_3() throws {
		let result = DataStorage.Gigabits.toMebibits(6.1)
		XCTAssertEqual(5817.413330078125, result, accuracy: 0.01)
	}

}

final class GigabytesTests: XCTestCase {
	func testConvertKnownGigabytesToBits_1() throws {
		let result = DataStorage.Gigabytes.toBits(0.004)
		XCTAssertEqual(32000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToBits_2() throws {
		let result = DataStorage.Gigabytes.toBits(0.012)
		XCTAssertEqual(96000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToBits_3() throws {
		let result = DataStorage.Gigabytes.toBits(3e-9)
		XCTAssertEqual(24.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKilobits_1() throws {
		let result = DataStorage.Gigabytes.toKilobits(0.009)
		XCTAssertEqual(72000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKilobits_2() throws {
		let result = DataStorage.Gigabytes.toKilobits(1.2e-4)
		XCTAssertEqual(960.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKilobits_3() throws {
		let result = DataStorage.Gigabytes.toKilobits(0.0078)
		XCTAssertEqual(62400.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMegabits_1() throws {
		let result = DataStorage.Gigabytes.toMegabits(0.0078)
		XCTAssertEqual(62.4, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMegabits_2() throws {
		let result = DataStorage.Gigabytes.toMegabits(0.01)
		XCTAssertEqual(80.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMegabits_3() throws {
		let result = DataStorage.Gigabytes.toMegabits(0.001234)
		XCTAssertEqual(9.872, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToGigabits_1() throws {
		let result = DataStorage.Gigabytes.toGigabits(5.0)
		XCTAssertEqual(40.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToGigabits_2() throws {
		let result = DataStorage.Gigabytes.toGigabits(1.2)
		XCTAssertEqual(9.6, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToGigabits_3() throws {
		let result = DataStorage.Gigabytes.toGigabits(0.01)
		XCTAssertEqual(0.08, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToTerabits_1() throws {
		let result = DataStorage.Gigabytes.toTerabits(70.0)
		XCTAssertEqual(0.56, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToTerabits_2() throws {
		let result = DataStorage.Gigabytes.toTerabits(9001.0)
		XCTAssertEqual(72.008, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToTerabits_3() throws {
		let result = DataStorage.Gigabytes.toTerabits(768123.9)
		XCTAssertEqual(6144.9912, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKilobytes_1() throws {
		let result = DataStorage.Gigabytes.toKilobytes(0.2)
		XCTAssertEqual(200000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKilobytes_2() throws {
		let result = DataStorage.Gigabytes.toKilobytes(0.009)
		XCTAssertEqual(9000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKilobytes_3() throws {
		let result = DataStorage.Gigabytes.toKilobytes(0.00123)
		XCTAssertEqual(1230.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMegabytes_1() throws {
		let result = DataStorage.Gigabytes.toMegabytes(0.9)
		XCTAssertEqual(900.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMegabytes_2() throws {
		let result = DataStorage.Gigabytes.toMegabytes(12.0)
		XCTAssertEqual(12000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMegabytes_3() throws {
		let result = DataStorage.Gigabytes.toMegabytes(35.6)
		XCTAssertEqual(35600.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToTerabytes_1() throws {
		let result = DataStorage.Gigabytes.toTerabytes(35.6)
		XCTAssertEqual(0.0356, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToTerabytes_2() throws {
		let result = DataStorage.Gigabytes.toTerabytes(100.23)
		XCTAssertEqual(0.10023, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToTerabytes_3() throws {
		let result = DataStorage.Gigabytes.toTerabytes(900100.0)
		XCTAssertEqual(900.1, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKibibits_1() throws {
		let result = DataStorage.Gigabytes.toKibibits(0.05)
		XCTAssertEqual(390625.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKibibits_2() throws {
		let result = DataStorage.Gigabytes.toKibibits(0.008)
		XCTAssertEqual(62500.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToKibibits_3() throws {
		let result = DataStorage.Gigabytes.toKibibits(0.00123)
		XCTAssertEqual(9609.375, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMebibits_1() throws {
		let result = DataStorage.Gigabytes.toMebibits(0.009)
		XCTAssertEqual(68.66451, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMebibits_2() throws {
		let result = DataStorage.Gigabytes.toMebibits(1.2)
		XCTAssertEqual(9155.268, result, accuracy: 0.01)
	}

	func testConvertKnownGigabytesToMebibits_3() throws {
		let result = DataStorage.Gigabytes.toMebibits(19.2)
		XCTAssertEqual(146484.288, result, accuracy: 0.01)
	}

}

final class KibibitsTests: XCTestCase {
	func testConvertKnownKibibitsToBits_1() throws {
		let result = DataStorage.Kibibits.toBits(2.0)
		XCTAssertEqual(2048.0, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToBits_2() throws {
		let result = DataStorage.Kibibits.toBits(9.0)
		XCTAssertEqual(9216.0, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToBits_3() throws {
		let result = DataStorage.Kibibits.toBits(17.8)
		XCTAssertEqual(18227.2, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToKilobits_1() throws {
		let result = DataStorage.Kibibits.toKilobits(6.2)
		XCTAssertEqual(6.3488, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToKilobits_2() throws {
		let result = DataStorage.Kibibits.toKilobits(0.9)
		XCTAssertEqual(0.9216, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToKilobits_3() throws {
		let result = DataStorage.Kibibits.toKilobits(87.0)
		XCTAssertEqual(89.088, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMegabits_1() throws {
		let result = DataStorage.Kibibits.toMegabits(87.0)
		XCTAssertEqual(0.089088, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMegabits_2() throws {
		let result = DataStorage.Kibibits.toMegabits(12.34)
		XCTAssertEqual(0.01263616, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMegabits_3() throws {
		let result = DataStorage.Kibibits.toMegabits(123456.0)
		XCTAssertEqual(126.418879, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToGigabits_1() throws {
		let result = DataStorage.Kibibits.toGigabits(123456.0)
		XCTAssertEqual(0.126418944, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToGigabits_2() throws {
		let result = DataStorage.Kibibits.toGigabits(8000000.0)
		XCTAssertEqual(8.192, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToGigabits_3() throws {
		let result = DataStorage.Kibibits.toGigabits(1276876.0)
		XCTAssertEqual(1.307521024, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToTerabits_1() throws {
		let result = DataStorage.Kibibits.toTerabits(800000000.0)
		XCTAssertEqual(0.8192, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToTerabits_2() throws {
		let result = DataStorage.Kibibits.toTerabits(1.5e12)
		XCTAssertEqual(1536.0, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToTerabits_3() throws {
		let result = DataStorage.Kibibits.toTerabits(9999999.0)
		XCTAssertEqual(0.01023999898, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToKilobytes_1() throws {
		let result = DataStorage.Kibibits.toKilobytes(919.0)
		XCTAssertEqual(117.632, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToKilobytes_2() throws {
		let result = DataStorage.Kibibits.toKilobytes(77.4)
		XCTAssertEqual(9.9072, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToKilobytes_3() throws {
		let result = DataStorage.Kibibits.toKilobytes(109.109)
		XCTAssertEqual(13.965952, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMegabytes_1() throws {
		let result = DataStorage.Kibibits.toMegabytes(1000.0)
		XCTAssertEqual(0.128, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMegabytes_2() throws {
		let result = DataStorage.Kibibits.toMegabytes(800.123)
		XCTAssertEqual(0.102415744, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMegabytes_3() throws {
		let result = DataStorage.Kibibits.toMegabytes(123456.0)
		XCTAssertEqual(15.802368, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToGigabytes_1() throws {
		let result = DataStorage.Kibibits.toGigabytes(12345678.0)
		XCTAssertEqual(1.580347926, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToGigabytes_2() throws {
		let result = DataStorage.Kibibits.toGigabytes(8e12)
		XCTAssertEqual(1024000.00, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToGigabytes_3() throws {
		let result = DataStorage.Kibibits.toGigabytes(1.2e5)
		XCTAssertEqual(0.01536, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToTerabytes_1() throws {
		let result = DataStorage.Kibibits.toTerabytes(120000000.0)
		XCTAssertEqual(0.01536, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToTerabytes_2() throws {
		let result = DataStorage.Kibibits.toTerabytes(88e12)
		XCTAssertEqual(11264.0, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToTerabytes_3() throws {
		let result = DataStorage.Kibibits.toTerabytes(9000000.0)
		XCTAssertEqual(0.009216, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMebibits_1() throws {
		let result = DataStorage.Kibibits.toMebibits(600.0)
		XCTAssertEqual(0.5859375, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMebibits_2() throws {
		let result = DataStorage.Kibibits.toMebibits(12345.0)
		XCTAssertEqual(12.055664, result, accuracy: 0.01)
	}

	func testConvertKnownKibibitsToMebibits_3() throws {
		let result = DataStorage.Kibibits.toMebibits(101.0)
		XCTAssertEqual(0.0986328, result, accuracy: 0.01)
	}

}

final class KilobitsTests: XCTestCase {
	func testConvertKnownKilobitsToBits_1() throws {
		let result = DataStorage.Kilobits.toBits(9.0)
		XCTAssertEqual(9000.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToBits_2() throws {
		let result = DataStorage.Kilobits.toBits(6.7)
		XCTAssertEqual(6700.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToBits_3() throws {
		let result = DataStorage.Kilobits.toBits(1.2345)
		XCTAssertEqual(1234.5, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMegabits_1() throws {
		let result = DataStorage.Kilobits.toMegabits(900.0)
		XCTAssertEqual(0.9, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMegabits_2() throws {
		let result = DataStorage.Kilobits.toMegabits(12345.0)
		XCTAssertEqual(12.345, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMegabits_3() throws {
		let result = DataStorage.Kilobits.toMegabits(9988.0)
		XCTAssertEqual(9.988, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToGigabits_1() throws {
		let result = DataStorage.Kilobits.toGigabits(123456.0)
		XCTAssertEqual(0.123456, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToGigabits_2() throws {
		let result = DataStorage.Kilobits.toGigabits(8000700.0)
		XCTAssertEqual(8.0007, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToGigabits_3() throws {
		let result = DataStorage.Kilobits.toGigabits(191987578.0)
		XCTAssertEqual(191.987578, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToTerabits_1() throws {
		let result = DataStorage.Kilobits.toTerabits(191987578.0)
		XCTAssertEqual(0.191987578, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToTerabits_2() throws {
		let result = DataStorage.Kilobits.toTerabits(9010081903.0)
		XCTAssertEqual(9.010081903, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToTerabits_3() throws {
		let result = DataStorage.Kilobits.toTerabits(123456789.0)
		XCTAssertEqual(0.123456789, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToKilobytes_1() throws {
		let result = DataStorage.Kilobits.toKilobytes(80.0)
		XCTAssertEqual(10.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToKilobytes_2() throws {
		let result = DataStorage.Kilobits.toKilobytes(15.67)
		XCTAssertEqual(1.95875, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToKilobytes_3() throws {
		let result = DataStorage.Kilobits.toKilobytes(8007.09)
		XCTAssertEqual(1000.88625, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMegabytes_1() throws {
		let result = DataStorage.Kilobits.toMegabytes(123456.0)
		XCTAssertEqual(15.432, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMegabytes_2() throws {
		let result = DataStorage.Kilobits.toMegabytes(998877.0)
		XCTAssertEqual(124.859625, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMegabytes_3() throws {
		let result = DataStorage.Kilobits.toMegabytes(10090.0)
		XCTAssertEqual(1.26125, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToGigabytes_1() throws {
		let result = DataStorage.Kilobits.toGigabytes(1828972.0)
		XCTAssertEqual(0.2286215, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToGigabytes_2() throws {
		let result = DataStorage.Kilobits.toGigabytes(879860.8)
		XCTAssertEqual(0.1099826, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToGigabytes_3() throws {
		let result = DataStorage.Kilobits.toGigabytes(78178971.0)
		XCTAssertEqual(9.772371375, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToTerabytes_1() throws {
		let result = DataStorage.Kilobits.toTerabytes(1234567891.0)
		XCTAssertEqual(0.154320986375, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToTerabytes_2() throws {
		let result = DataStorage.Kilobits.toTerabytes(999999098.0)
		XCTAssertEqual(0.12499988725, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToTerabytes_3() throws {
		let result = DataStorage.Kilobits.toTerabytes(84618364142.0)
		XCTAssertEqual(10.57729551775, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToKibibits_1() throws {
		let result = DataStorage.Kilobits.toKibibits(89.1)
		XCTAssertEqual(87.01172, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToKibibits_2() throws {
		let result = DataStorage.Kilobits.toKibibits(7.1)
		XCTAssertEqual(6.93359, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToKibibits_3() throws {
		let result = DataStorage.Kilobits.toKibibits(438.0)
		XCTAssertEqual(427.734, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMebibits_1() throws {
		let result = DataStorage.Kilobits.toMebibits(77790.0)
		XCTAssertEqual(74.186325, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMebibits_2() throws {
		let result = DataStorage.Kilobits.toMebibits(123456.0)
		XCTAssertEqual(117.736816, result, accuracy: 0.01)
	}

	func testConvertKnownKilobitsToMebibits_3() throws {
		let result = DataStorage.Kilobits.toMebibits(23972.0)
		XCTAssertEqual(22.861481, result, accuracy: 0.01)
	}

}

final class KilobytesTests: XCTestCase {
	func testConvertKnownKilobytesToBits_1() throws {
		let result = DataStorage.Kilobytes.toBits(123.456)
		XCTAssertEqual(987648.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToBits_2() throws {
		let result = DataStorage.Kilobytes.toBits(900.0)
		XCTAssertEqual(7.2e+6, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToBits_3() throws {
		let result = DataStorage.Kilobytes.toBits(100200.0)
		XCTAssertEqual(801600000.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToKilobits_1() throws {
		let result = DataStorage.Kilobytes.toKilobits(4.0)
		XCTAssertEqual(32.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToKilobits_2() throws {
		let result = DataStorage.Kilobytes.toKilobits(1.2)
		XCTAssertEqual(9.6, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToKilobits_3() throws {
		let result = DataStorage.Kilobytes.toKilobits(88.1)
		XCTAssertEqual(704.8, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMegabits_1() throws {
		let result = DataStorage.Kilobytes.toMegabits(88.1)
		XCTAssertEqual(0.7048, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMegabits_2() throws {
		let result = DataStorage.Kilobytes.toMegabits(7.1)
		XCTAssertEqual(0.0568, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMegabits_3() throws {
		let result = DataStorage.Kilobytes.toMegabits(12.8)
		XCTAssertEqual(0.1024, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToGigabits_1() throws {
		let result = DataStorage.Kilobytes.toGigabits(10080.0)
		XCTAssertEqual(0.08064, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToGigabits_2() throws {
		let result = DataStorage.Kilobytes.toGigabits(4.5e+9)
		XCTAssertEqual(36000.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToGigabits_3() throws {
		let result = DataStorage.Kilobytes.toGigabits(271279.0)
		XCTAssertEqual(2.170232, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToTerabits_1() throws {
		let result = DataStorage.Kilobytes.toTerabits(9009000.0)
		XCTAssertEqual(0.072072, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToTerabits_2() throws {
		let result = DataStorage.Kilobytes.toTerabits(7.2e9)
		XCTAssertEqual(57.6, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToTerabits_3() throws {
		let result = DataStorage.Kilobytes.toTerabits(100100100900.0)
		XCTAssertEqual(800.8008072, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMegabytes_1() throws {
		let result = DataStorage.Kilobytes.toMegabytes(1009.0)
		XCTAssertEqual(1.009, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMegabytes_2() throws {
		let result = DataStorage.Kilobytes.toMegabytes(8899.0)
		XCTAssertEqual(8.899, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMegabytes_3() throws {
		let result = DataStorage.Kilobytes.toMegabytes(619.0)
		XCTAssertEqual(0.619, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToGigabytes_1() throws {
		let result = DataStorage.Kilobytes.toGigabytes(900800.0)
		XCTAssertEqual(0.9008, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToGigabytes_2() throws {
		let result = DataStorage.Kilobytes.toGigabytes(1234567.0)
		XCTAssertEqual(1.234567, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToGigabytes_3() throws {
		let result = DataStorage.Kilobytes.toGigabytes(7.9e9)
		XCTAssertEqual(7900.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToTerabytes_1() throws {
		let result = DataStorage.Kilobytes.toTerabytes(0.9)
		XCTAssertEqual(9e-10, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToTerabytes_2() throws {
		let result = DataStorage.Kilobytes.toTerabytes(140000000.0)
		XCTAssertEqual(0.14, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToTerabytes_3() throws {
		let result = DataStorage.Kilobytes.toTerabytes(7.0)
		XCTAssertEqual(7e-9, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToKibibits_1() throws {
		let result = DataStorage.Kilobytes.toKibibits(0.009)
		XCTAssertEqual(0.0703125, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToKibibits_2() throws {
		let result = DataStorage.Kilobytes.toKibibits(6e+3)
		XCTAssertEqual(46875.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToKibibits_3() throws {
		let result = DataStorage.Kilobytes.toKibibits(1.23)
		XCTAssertEqual(9.609375, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMebibits_1() throws {
		let result = DataStorage.Kilobytes.toMebibits(70.0)
		XCTAssertEqual(0.534058, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMebibits_2() throws {
		let result = DataStorage.Kilobytes.toMebibits(9.0)
		XCTAssertEqual(0.0686646, result, accuracy: 0.01)
	}

	func testConvertKnownKilobytesToMebibits_3() throws {
		let result = DataStorage.Kilobytes.toMebibits(10022.0)
		XCTAssertEqual(76.461792, result, accuracy: 0.01)
	}

}

final class MebibitsTests: XCTestCase {
	func testConvertKnownMebibitsToBits_1() throws {
		let result = DataStorage.Mebibits.toBits(0.9)
		XCTAssertEqual(943718.4, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToBits_2() throws {
		let result = DataStorage.Mebibits.toBits(0.006)
		XCTAssertEqual(6291.456, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToBits_3() throws {
		let result = DataStorage.Mebibits.toBits(2.0)
		XCTAssertEqual(2097152.0, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKilobits_1() throws {
		let result = DataStorage.Mebibits.toKilobits(0.8)
		XCTAssertEqual(838.861, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKilobits_2() throws {
		let result = DataStorage.Mebibits.toKilobits(2.0)
		XCTAssertEqual(2097.15, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKilobits_3() throws {
		let result = DataStorage.Mebibits.toKilobits(0.23)
		XCTAssertEqual(241.1725, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToMegabits_1() throws {
		let result = DataStorage.Mebibits.toMegabits(0.9)
		XCTAssertEqual(0.943718, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToMegabits_2() throws {
		let result = DataStorage.Mebibits.toMegabits(12.3)
		XCTAssertEqual(12.89748, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToMegabits_3() throws {
		let result = DataStorage.Mebibits.toMegabits(8.1)
		XCTAssertEqual(8.49347, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToGigabits_1() throws {
		let result = DataStorage.Mebibits.toGigabits(12345.0)
		XCTAssertEqual(12.944671, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToGigabits_2() throws {
		let result = DataStorage.Mebibits.toGigabits(100.0)
		XCTAssertEqual(0.104858, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToGigabits_3() throws {
		let result = DataStorage.Mebibits.toGigabits(999.9)
		XCTAssertEqual(1.0484711, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToTerabits_1() throws {
		let result = DataStorage.Mebibits.toTerabits(100009.0)
		XCTAssertEqual(0.104867037, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToTerabits_2() throws {
		let result = DataStorage.Mebibits.toTerabits(9876543.0)
		XCTAssertEqual(10.35630595, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToTerabits_3() throws {
		let result = DataStorage.Mebibits.toTerabits(1000900.0)
		XCTAssertEqual(1.049519718, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKilobytes_1() throws {
		let result = DataStorage.Mebibits.toKilobytes(4.0)
		XCTAssertEqual(524.288, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKilobytes_2() throws {
		let result = DataStorage.Mebibits.toKilobytes(1.45)
		XCTAssertEqual(190.0544, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKilobytes_3() throws {
		let result = DataStorage.Mebibits.toKilobytes(88.11)
		XCTAssertEqual(11548.754, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToMegabytes_1() throws {
		let result = DataStorage.Mebibits.toMegabytes(109.0)
		XCTAssertEqual(14.2868, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToMegabytes_2() throws {
		let result = DataStorage.Mebibits.toMegabytes(55.67)
		XCTAssertEqual(7.2967782, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToMegabytes_3() throws {
		let result = DataStorage.Mebibits.toMegabytes(45678.0)
		XCTAssertEqual(5987.1068, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToGigabytes_1() throws {
		let result = DataStorage.Mebibits.toGigabytes(4000.0)
		XCTAssertEqual(0.524288311, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToGigabytes_2() throws {
		let result = DataStorage.Mebibits.toGigabytes(90100.0)
		XCTAssertEqual(11.80959421, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToGigabytes_3() throws {
		let result = DataStorage.Mebibits.toGigabytes(1009.0)
		XCTAssertEqual(0.132251727, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToTerabytes_1() throws {
		let result = DataStorage.Mebibits.toTerabytes(1000009.0)
		XCTAssertEqual(0.1310731796, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToTerabytes_2() throws {
		let result = DataStorage.Mebibits.toTerabytes(90808080.0)
		XCTAssertEqual(11.902396662, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToTerabytes_3() throws {
		let result = DataStorage.Mebibits.toTerabytes(5.2e12)
		XCTAssertEqual(681574.4, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKibibits_1() throws {
		let result = DataStorage.Mebibits.toKibibits(5.0)
		XCTAssertEqual(5120.0, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKibibits_2() throws {
		let result = DataStorage.Mebibits.toKibibits(1234.56)
		XCTAssertEqual(1264189.44, result, accuracy: 0.01)
	}

	func testConvertKnownMebibitsToKibibits_3() throws {
		let result = DataStorage.Mebibits.toKibibits(505.0)
		XCTAssertEqual(517120.0, result, accuracy: 0.01)
	}

}

final class MegabitsTests: XCTestCase {
	func testConvertKnownMegabitsToBits_1() throws {
		let result = DataStorage.Megabits.toBits(0.34)
		XCTAssertEqual(340000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToBits_2() throws {
		let result = DataStorage.Megabits.toBits(9.12)
		XCTAssertEqual(9120000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToBits_3() throws {
		let result = DataStorage.Megabits.toBits(0.987)
		XCTAssertEqual(987000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKilobits_1() throws {
		let result = DataStorage.Megabits.toKilobits(0.77)
		XCTAssertEqual(770.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKilobits_2() throws {
		let result = DataStorage.Megabits.toKilobits(5.0)
		XCTAssertEqual(5000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKilobits_3() throws {
		let result = DataStorage.Megabits.toKilobits(0.987)
		XCTAssertEqual(987.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToGigabits_1() throws {
		let result = DataStorage.Megabits.toGigabits(900.0)
		XCTAssertEqual(0.9, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToGigabits_2() throws {
		let result = DataStorage.Megabits.toGigabits(12345.0)
		XCTAssertEqual(12.345, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToGigabits_3() throws {
		let result = DataStorage.Megabits.toGigabits(189.1)
		XCTAssertEqual(0.1891, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToTerabits_1() throws {
		let result = DataStorage.Megabits.toTerabits(100200300.0)
		XCTAssertEqual(100.2003, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToTerabits_2() throws {
		let result = DataStorage.Megabits.toTerabits(99887777.0)
		XCTAssertEqual(99.887777, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToTerabits_3() throws {
		let result = DataStorage.Megabits.toTerabits(80009.0)
		XCTAssertEqual(0.080009, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKilobytes_1() throws {
		let result = DataStorage.Megabits.toKilobytes(9.0)
		XCTAssertEqual(1125.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKilobytes_2() throws {
		let result = DataStorage.Megabits.toKilobytes(1.23)
		XCTAssertEqual(153.75, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKilobytes_3() throws {
		let result = DataStorage.Megabits.toKilobytes(98.1)
		XCTAssertEqual(12262.5, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToMegabytes_1() throws {
		let result = DataStorage.Megabits.toMegabytes(98.1)
		XCTAssertEqual(12.2625, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToMegabytes_2() throws {
		let result = DataStorage.Megabits.toMegabytes(10.9)
		XCTAssertEqual(1.3625, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToMegabytes_3() throws {
		let result = DataStorage.Megabits.toMegabytes(888.123)
		XCTAssertEqual(111.015375, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToGigabytes_1() throws {
		let result = DataStorage.Megabits.toGigabytes(900.0)
		XCTAssertEqual(0.1125, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToGigabytes_2() throws {
		let result = DataStorage.Megabits.toGigabytes(10123.0)
		XCTAssertEqual(1.265375, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToGigabytes_3() throws {
		let result = DataStorage.Megabits.toGigabytes(9988.0)
		XCTAssertEqual(1.2485, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToTerabytes_1() throws {
		let result = DataStorage.Megabits.toTerabytes(998877.0)
		XCTAssertEqual(0.124859625, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToTerabytes_2() throws {
		let result = DataStorage.Megabits.toTerabytes(100200400.0)
		XCTAssertEqual(12.5250375, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToTerabytes_3() throws {
		let result = DataStorage.Megabits.toTerabytes(9008877.0)
		XCTAssertEqual(1.126109625, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKibibits_1() throws {
		let result = DataStorage.Megabits.toKibibits(12.0)
		XCTAssertEqual(11718.756, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKibibits_2() throws {
		let result = DataStorage.Megabits.toKibibits(0.9)
		XCTAssertEqual(878.906, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToKibibits_3() throws {
		let result = DataStorage.Megabits.toKibibits(1.23)
		XCTAssertEqual(1201.172, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToMebibits_1() throws {
		let result = DataStorage.Megabits.toMebibits(4.5)
		XCTAssertEqual(4.29153, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToMebibits_2() throws {
		let result = DataStorage.Megabits.toMebibits(0.8)
		XCTAssertEqual(0.762939, result, accuracy: 0.01)
	}

	func testConvertKnownMegabitsToMebibits_3() throws {
		let result = DataStorage.Megabits.toMebibits(900.0)
		XCTAssertEqual(858.307, result, accuracy: 0.01)
	}

}

final class MegabytesTests: XCTestCase {
	func testConvertKnownMegabytesToBits_1() throws {
		let result = DataStorage.Megabytes.toBits(0.04)
		XCTAssertEqual(320000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToBits_2() throws {
		let result = DataStorage.Megabytes.toBits(0.0091)
		XCTAssertEqual(72800.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToBits_3() throws {
		let result = DataStorage.Megabytes.toBits(3e-5)
		XCTAssertEqual(240.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKilobits_1() throws {
		let result = DataStorage.Megabytes.toKilobits(6.0)
		XCTAssertEqual(48000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKilobits_2() throws {
		let result = DataStorage.Megabytes.toKilobits(0.3)
		XCTAssertEqual(2400.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKilobits_3() throws {
		let result = DataStorage.Megabytes.toKilobits(0.009)
		XCTAssertEqual(72.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToMegabits_1() throws {
		let result = DataStorage.Megabytes.toMegabits(3.0)
		XCTAssertEqual(24.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToMegabits_2() throws {
		let result = DataStorage.Megabytes.toMegabits(0.9)
		XCTAssertEqual(7.2, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToMegabits_3() throws {
		let result = DataStorage.Megabytes.toMegabits(13.0)
		XCTAssertEqual(104.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToGigabits_1() throws {
		let result = DataStorage.Megabytes.toGigabits(13.0)
		XCTAssertEqual(0.104, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToGigabits_2() throws {
		let result = DataStorage.Megabytes.toGigabits(900.0)
		XCTAssertEqual(7.2, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToGigabits_3() throws {
		let result = DataStorage.Megabytes.toGigabits(18000.0)
		XCTAssertEqual(144.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToTerabits_1() throws {
		let result = DataStorage.Megabytes.toTerabits(18000.0)
		XCTAssertEqual(0.144, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToTerabits_2() throws {
		let result = DataStorage.Megabytes.toTerabits(9718290.0)
		XCTAssertEqual(77.74632, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToTerabits_3() throws {
		let result = DataStorage.Megabytes.toTerabits(9e12)
		XCTAssertEqual(72000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKilobytes_1() throws {
		let result = DataStorage.Megabytes.toKilobytes(6.0)
		XCTAssertEqual(6000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKilobytes_2() throws {
		let result = DataStorage.Megabytes.toKilobytes(0.9)
		XCTAssertEqual(900.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKilobytes_3() throws {
		let result = DataStorage.Megabytes.toKilobytes(123.4)
		XCTAssertEqual(123400.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToGigabytes_1() throws {
		let result = DataStorage.Megabytes.toGigabytes(123.4)
		XCTAssertEqual(0.1234, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToGigabytes_2() throws {
		let result = DataStorage.Megabytes.toGigabytes(900.0)
		XCTAssertEqual(0.9, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToGigabytes_3() throws {
		let result = DataStorage.Megabytes.toGigabytes(8e6)
		XCTAssertEqual(8000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToTerabytes_1() throws {
		let result = DataStorage.Megabytes.toTerabytes(80000.0)
		XCTAssertEqual(0.08, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToTerabytes_2() throws {
		let result = DataStorage.Megabytes.toTerabytes(12345678.0)
		XCTAssertEqual(12.345678, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToTerabytes_3() throws {
		let result = DataStorage.Megabytes.toTerabytes(900800.0)
		XCTAssertEqual(0.9008, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKibibits_1() throws {
		let result = DataStorage.Megabytes.toKibibits(6.0)
		XCTAssertEqual(46875.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKibibits_2() throws {
		let result = DataStorage.Megabytes.toKibibits(0.9)
		XCTAssertEqual(7031.25, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToKibibits_3() throws {
		let result = DataStorage.Megabytes.toKibibits(0.03)
		XCTAssertEqual(234.375, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToMebibits_1() throws {
		let result = DataStorage.Megabytes.toMebibits(0.03)
		XCTAssertEqual(0.2288818, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToMebibits_2() throws {
		let result = DataStorage.Megabytes.toMebibits(4.5)
		XCTAssertEqual(34.3323, result, accuracy: 0.01)
	}

	func testConvertKnownMegabytesToMebibits_3() throws {
		let result = DataStorage.Megabytes.toMebibits(80.1)
		XCTAssertEqual(611.1145, result, accuracy: 0.01)
	}

}

final class TerabitsTests: XCTestCase {
	func testConvertKnownTerabitsToBits_1() throws {
		let result = DataStorage.Terabits.toBits(0.0007)
		XCTAssertEqual(700000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToBits_2() throws {
		let result = DataStorage.Terabits.toBits(1.23e-6)
		XCTAssertEqual(1230000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToBits_3() throws {
		let result = DataStorage.Terabits.toBits(0.00098)
		XCTAssertEqual(980000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKilobits_1() throws {
		let result = DataStorage.Terabits.toKilobits(0.001)
		XCTAssertEqual(1000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKilobits_2() throws {
		let result = DataStorage.Terabits.toKilobits(6.1e-6)
		XCTAssertEqual(6100.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKilobits_3() throws {
		let result = DataStorage.Terabits.toKilobits(0.00009)
		XCTAssertEqual(90000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMegabits_1() throws {
		let result = DataStorage.Terabits.toMegabits(0.09)
		XCTAssertEqual(90000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMegabits_2() throws {
		let result = DataStorage.Terabits.toMegabits(3.5e-4)
		XCTAssertEqual(350.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMegabits_3() throws {
		let result = DataStorage.Terabits.toMegabits(0.0123)
		XCTAssertEqual(12300.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToGigabits_1() throws {
		let result = DataStorage.Terabits.toGigabits(0.9)
		XCTAssertEqual(900.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToGigabits_2() throws {
		let result = DataStorage.Terabits.toGigabits(1.45)
		XCTAssertEqual(1450.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToGigabits_3() throws {
		let result = DataStorage.Terabits.toGigabits(8.19)
		XCTAssertEqual(8190.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKilobytes_1() throws {
		let result = DataStorage.Terabits.toKilobytes(0.0009)
		XCTAssertEqual(112500.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKilobytes_2() throws {
		let result = DataStorage.Terabits.toKilobytes(3.14e-6)
		XCTAssertEqual(392.5, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKilobytes_3() throws {
		let result = DataStorage.Terabits.toKilobytes(0.001)
		XCTAssertEqual(125000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMegabytes_1() throws {
		let result = DataStorage.Terabits.toMegabytes(0.4)
		XCTAssertEqual(50000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMegabytes_2() throws {
		let result = DataStorage.Terabits.toMegabytes(3.9e-3)
		XCTAssertEqual(487.5, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMegabytes_3() throws {
		let result = DataStorage.Terabits.toMegabytes(0.007)
		XCTAssertEqual(875.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToGigabytes_1() throws {
		let result = DataStorage.Terabits.toGigabytes(0.009)
		XCTAssertEqual(1.125, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToGigabytes_2() throws {
		let result = DataStorage.Terabits.toGigabytes(0.00123)
		XCTAssertEqual(0.15375, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToGigabytes_3() throws {
		let result = DataStorage.Terabits.toGigabytes(8.1e-3)
		XCTAssertEqual(1.0125, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToTerabytes_1() throws {
		let result = DataStorage.Terabits.toTerabytes(0.3)
		XCTAssertEqual(0.0375, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToTerabytes_2() throws {
		let result = DataStorage.Terabits.toTerabytes(14.0)
		XCTAssertEqual(1.75, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToTerabytes_3() throws {
		let result = DataStorage.Terabits.toTerabytes(0.8)
		XCTAssertEqual(0.1, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKibibits_1() throws {
		let result = DataStorage.Terabits.toKibibits(0.0009)
		XCTAssertEqual(878906.25, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKibibits_2() throws {
		let result = DataStorage.Terabits.toKibibits(6.1e-6)
		XCTAssertEqual(5957.031, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToKibibits_3() throws {
		let result = DataStorage.Terabits.toKibibits(12e-9)
		XCTAssertEqual(11.71875, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMebibits_1() throws {
		let result = DataStorage.Terabits.toMebibits(0.9)
		XCTAssertEqual(858306.59999, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMebibits_2() throws {
		let result = DataStorage.Terabits.toMebibits(4.6e-3)
		XCTAssertEqual(4386.9, result, accuracy: 0.01)
	}

	func testConvertKnownTerabitsToMebibits_3() throws {
		let result = DataStorage.Terabits.toMebibits(0.00123)
		XCTAssertEqual(1173.0194092, result, accuracy: 0.01)
	}

}

final class TerabytesTests: XCTestCase {
	func testConvertKnownTerabytesToBits_1() throws {
		let result = DataStorage.Terabytes.toBits(0.00008)
		XCTAssertEqual(640000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToBits_2() throws {
		let result = DataStorage.Terabytes.toBits(1.2e-12)
		XCTAssertEqual(9.6, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToBits_3() throws {
		let result = DataStorage.Terabytes.toBits(9.0)
		XCTAssertEqual(7.2e+13, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKilobits_1() throws {
		let result = DataStorage.Terabytes.toKilobits(0.009)
		XCTAssertEqual(72000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKilobits_2() throws {
		let result = DataStorage.Terabytes.toKilobits(1.4e-6)
		XCTAssertEqual(11200.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKilobits_3() throws {
		let result = DataStorage.Terabytes.toKilobits(6.1e-5)
		XCTAssertEqual(488000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMegabits_1() throws {
		let result = DataStorage.Terabytes.toMegabits(0.005)
		XCTAssertEqual(40000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMegabits_2() throws {
		let result = DataStorage.Terabytes.toMegabits(0.000123)
		XCTAssertEqual(984.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMegabits_3() throws {
		let result = DataStorage.Terabytes.toMegabits(0.00006)
		XCTAssertEqual(480.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToGigabits_1() throws {
		let result = DataStorage.Terabytes.toGigabits(0.008)
		XCTAssertEqual(64.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToGigabits_2() throws {
		let result = DataStorage.Terabytes.toGigabits(3e-7)
		XCTAssertEqual(0.0024, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToGigabits_3() throws {
		let result = DataStorage.Terabytes.toGigabits(0.00023)
		XCTAssertEqual(1.84, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToTerabits_1() throws {
		let result = DataStorage.Terabytes.toTerabits(5.0)
		XCTAssertEqual(40.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToTerabits_2() throws {
		let result = DataStorage.Terabytes.toTerabits(1.23)
		XCTAssertEqual(9.84, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToTerabits_3() throws {
		let result = DataStorage.Terabytes.toTerabits(800.0)
		XCTAssertEqual(6400.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKilobytes_1() throws {
		let result = DataStorage.Terabytes.toKilobytes(0.0009)
		XCTAssertEqual(900000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKilobytes_2() throws {
		let result = DataStorage.Terabytes.toKilobytes(3.14e-7)
		XCTAssertEqual(314.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKilobytes_3() throws {
		let result = DataStorage.Terabytes.toKilobytes(0.00063)
		XCTAssertEqual(630000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMegabytes_1() throws {
		let result = DataStorage.Terabytes.toMegabytes(0.009)
		XCTAssertEqual(9000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMegabytes_2() throws {
		let result = DataStorage.Terabytes.toMegabytes(0.234)
		XCTAssertEqual(234000.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMegabytes_3() throws {
		let result = DataStorage.Terabytes.toMegabytes(2.0)
		XCTAssertEqual(2e+6, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToGigabytes_1() throws {
		let result = DataStorage.Terabytes.toGigabytes(2.7)
		XCTAssertEqual(2700.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToGigabytes_2() throws {
		let result = DataStorage.Terabytes.toGigabytes(0.9)
		XCTAssertEqual(900.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToGigabytes_3() throws {
		let result = DataStorage.Terabytes.toGigabytes(0.0123)
		XCTAssertEqual(12.3, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKibibits_1() throws {
		let result = DataStorage.Terabytes.toKibibits(0.0009)
		XCTAssertEqual(7031250.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKibibits_2() throws {
		let result = DataStorage.Terabytes.toKibibits(1.23e-5)
		XCTAssertEqual(96093.75, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToKibibits_3() throws {
		let result = DataStorage.Terabytes.toKibibits(0.0001)
		XCTAssertEqual(781250.0, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMebibits_1() throws {
		let result = DataStorage.Terabytes.toMebibits(0.01)
		XCTAssertEqual(76293.95, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMebibits_2() throws {
		let result = DataStorage.Terabytes.toMebibits(0.008)
		XCTAssertEqual(61035.156, result, accuracy: 0.01)
	}

	func testConvertKnownTerabytesToMebibits_3() throws {
		let result = DataStorage.Terabytes.toMebibits(2.0)
		XCTAssertEqual(15258789.0625, result, accuracy: 0.01)
	}

}

