// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import XCTest
@testable import SwiftUnits

final class GigahertzTests: XCTestCase {
	func testConvertKnownGigahertzToHertz_1() throws {
		let result = Frequency.Gigahertz.toHertz(0.009)
		XCTAssertEqual(9000000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigahertzToHertz_2() throws {
		let result = Frequency.Gigahertz.toHertz(0.000123)
		XCTAssertEqual(123000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigahertzToHertz_3() throws {
		let result = Frequency.Gigahertz.toHertz(0.0000456)
		XCTAssertEqual(45600.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigahertzToKilohertz_1() throws {
		let result = Frequency.Gigahertz.toKilohertz(0.009)
		XCTAssertEqual(9000.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigahertzToKilohertz_2() throws {
		let result = Frequency.Gigahertz.toKilohertz(1e-5)
		XCTAssertEqual(10.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigahertzToKilohertz_3() throws {
		let result = Frequency.Gigahertz.toKilohertz(0.000065)
		XCTAssertEqual(65.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigahertzToMegahertz_1() throws {
		let result = Frequency.Gigahertz.toMegahertz(0.9)
		XCTAssertEqual(900.0, result, accuracy: 0.01)
	}

	func testConvertKnownGigahertzToMegahertz_2() throws {
		let result = Frequency.Gigahertz.toMegahertz(0.0123)
		XCTAssertEqual(12.3, result, accuracy: 0.01)
	}

	func testConvertKnownGigahertzToMegahertz_3() throws {
		let result = Frequency.Gigahertz.toMegahertz(5.0)
		XCTAssertEqual(5000.0, result, accuracy: 0.01)
	}

}

final class HertzTests: XCTestCase {
	func testConvertKnownHertzToKilohertz_1() throws {
		let result = Frequency.Hertz.toKilohertz(800.0)
		XCTAssertEqual(0.8, result, accuracy: 0.01)
	}

	func testConvertKnownHertzToKilohertz_2() throws {
		let result = Frequency.Hertz.toKilohertz(1506.9)
		XCTAssertEqual(1.5069, result, accuracy: 0.01)
	}

	func testConvertKnownHertzToKilohertz_3() throws {
		let result = Frequency.Hertz.toKilohertz(5000.0)
		XCTAssertEqual(5.0, result, accuracy: 0.01)
	}

	func testConvertKnownHertzToMegahertz_1() throws {
		let result = Frequency.Hertz.toMegahertz(900009.0)
		XCTAssertEqual(0.900009, result, accuracy: 0.01)
	}

	func testConvertKnownHertzToMegahertz_2() throws {
		let result = Frequency.Hertz.toMegahertz(160000.0)
		XCTAssertEqual(0.16, result, accuracy: 0.01)
	}

	func testConvertKnownHertzToMegahertz_3() throws {
		let result = Frequency.Hertz.toMegahertz(888888.0)
		XCTAssertEqual(0.888888, result, accuracy: 0.01)
	}

	func testConvertKnownHertzToGigahertz_1() throws {
		let result = Frequency.Hertz.toGigahertz(100900900.0)
		XCTAssertEqual(0.1009009, result, accuracy: 0.01)
	}

	func testConvertKnownHertzToGigahertz_2() throws {
		let result = Frequency.Hertz.toGigahertz(9.0)
		XCTAssertEqual(9e-9, result, accuracy: 0.01)
	}

	func testConvertKnownHertzToGigahertz_3() throws {
		let result = Frequency.Hertz.toGigahertz(90909090.0)
		XCTAssertEqual(0.09090909, result, accuracy: 0.01)
	}

}

final class KilohertzTests: XCTestCase {
	func testConvertKnownKilohertzToHertz_1() throws {
		let result = Frequency.Kilohertz.toHertz(90.90909)
		XCTAssertEqual(90909.09, result, accuracy: 0.01)
	}

	func testConvertKnownKilohertzToHertz_2() throws {
		let result = Frequency.Kilohertz.toHertz(0.12345)
		XCTAssertEqual(123.45, result, accuracy: 0.01)
	}

	func testConvertKnownKilohertzToHertz_3() throws {
		let result = Frequency.Kilohertz.toHertz(500.0)
		XCTAssertEqual(500000.0, result, accuracy: 0.01)
	}

	func testConvertKnownKilohertzToMegahertz_1() throws {
		let result = Frequency.Kilohertz.toMegahertz(909.0)
		XCTAssertEqual(0.909, result, accuracy: 0.01)
	}

	func testConvertKnownKilohertzToMegahertz_2() throws {
		let result = Frequency.Kilohertz.toMegahertz(123456.0)
		XCTAssertEqual(123.456, result, accuracy: 0.01)
	}

	func testConvertKnownKilohertzToMegahertz_3() throws {
		let result = Frequency.Kilohertz.toMegahertz(900.0)
		XCTAssertEqual(0.9, result, accuracy: 0.01)
	}

	func testConvertKnownKilohertzToGigahertz_1() throws {
		let result = Frequency.Kilohertz.toGigahertz(987654.0)
		XCTAssertEqual(0.987654, result, accuracy: 0.01)
	}

	func testConvertKnownKilohertzToGigahertz_2() throws {
		let result = Frequency.Kilohertz.toGigahertz(10000.0)
		XCTAssertEqual(0.01, result, accuracy: 0.01)
	}

	func testConvertKnownKilohertzToGigahertz_3() throws {
		let result = Frequency.Kilohertz.toGigahertz(90090.0)
		XCTAssertEqual(0.09009, result, accuracy: 0.01)
	}

}

final class MegahertzTests: XCTestCase {
	func testConvertKnownMegahertzToHertz_1() throws {
		let result = Frequency.Megahertz.toHertz(0.9)
		XCTAssertEqual(900000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegahertzToHertz_2() throws {
		let result = Frequency.Megahertz.toHertz(0.001)
		XCTAssertEqual(1000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegahertzToHertz_3() throws {
		let result = Frequency.Megahertz.toHertz(0.091)
		XCTAssertEqual(91000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegahertzToKilohertz_1() throws {
		let result = Frequency.Megahertz.toKilohertz(0.87)
		XCTAssertEqual(870.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegahertzToKilohertz_2() throws {
		let result = Frequency.Megahertz.toKilohertz(12.0)
		XCTAssertEqual(12000.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegahertzToKilohertz_3() throws {
		let result = Frequency.Megahertz.toKilohertz(88.1)
		XCTAssertEqual(88100.0, result, accuracy: 0.01)
	}

	func testConvertKnownMegahertzToGigahertz_1() throws {
		let result = Frequency.Megahertz.toGigahertz(798.0)
		XCTAssertEqual(0.798, result, accuracy: 0.01)
	}

	func testConvertKnownMegahertzToGigahertz_2() throws {
		let result = Frequency.Megahertz.toGigahertz(900.0)
		XCTAssertEqual(0.9, result, accuracy: 0.01)
	}

	func testConvertKnownMegahertzToGigahertz_3() throws {
		let result = Frequency.Megahertz.toGigahertz(579.1)
		XCTAssertEqual(0.5791, result, accuracy: 0.01)
	}

}

