// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import XCTest
@testable import SwiftUnits

final class MechanicalHorsePowerTests: XCTestCase {
	func testConvertKnownMechanicalHorsePowerToMetricHorsePower_1() throws {
		let result = Power.MechanicalHorsePower.toMetricHorsePower(65.0971)
		XCTAssertEqual(65.9999749, result, accuracy: 0.01)
	}

	func testConvertKnownMechanicalHorsePowerToMetricHorsePower_2() throws {
		let result = Power.MechanicalHorsePower.toMetricHorsePower(121.317)
		XCTAssertEqual(122.9996, result, accuracy: 0.01)
	}

	func testConvertKnownMechanicalHorsePowerToMetricHorsePower_3() throws {
		let result = Power.MechanicalHorsePower.toMetricHorsePower(86.7962)
		XCTAssertEqual(88.0, result, accuracy: 0.01)
	}

}

final class MetricHorsePowerTests: XCTestCase {
	func testConvertKnownMetricHorsePowerToMechanicalHorsePower_1() throws {
		let result = Power.MetricHorsePower.toMechanicalHorsePower(126.734)
		XCTAssertEqual(125.0, result, accuracy: 0.01)
	}

	func testConvertKnownMetricHorsePowerToMechanicalHorsePower_2() throws {
		let result = Power.MetricHorsePower.toMechanicalHorsePower(91.2483)
		XCTAssertEqual(90.0, result, accuracy: 0.01)
	}

	func testConvertKnownMetricHorsePowerToMechanicalHorsePower_3() throws {
		let result = Power.MetricHorsePower.toMechanicalHorsePower(425.825)
		XCTAssertEqual(419.9997, result, accuracy: 0.01)
	}

}

