// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import XCTest
@testable import SwiftUnits

final class AtmospheresTests: XCTestCase {
	func testConvertKnownAtmospheresTobars_1() throws {
		let result = Pressure.Atmospheres.tobars(6.0)
		XCTAssertEqual(6.0795, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTobars_2() throws {
		let result = Pressure.Atmospheres.tobars(1.2)
		XCTAssertEqual(1.2159, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTobars_3() throws {
		let result = Pressure.Atmospheres.tobars(0.8)
		XCTAssertEqual(0.8106, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTopascals_1() throws {
		let result = Pressure.Atmospheres.topascals(0.8)
		XCTAssertEqual(81060.0, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTopascals_2() throws {
		let result = Pressure.Atmospheres.topascals(1.2)
		XCTAssertEqual(121590.0, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTopascals_3() throws {
		let result = Pressure.Atmospheres.topascals(0.45)
		XCTAssertEqual(45596.25, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTotorrs_1() throws {
		let result = Pressure.Atmospheres.totorrs(0.45)
		XCTAssertEqual(342.0, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTotorrs_2() throws {
		let result = Pressure.Atmospheres.totorrs(1.2)
		XCTAssertEqual(912.0, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTotorrs_3() throws {
		let result = Pressure.Atmospheres.totorrs(6.0)
		XCTAssertEqual(4560.0, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTopsi_1() throws {
		let result = Pressure.Atmospheres.topsi(6.0)
		XCTAssertEqual(88.1757, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTopsi_2() throws {
		let result = Pressure.Atmospheres.topsi(0.4)
		XCTAssertEqual(5.87838, result, accuracy: 0.01)
	}

	func testConvertKnownAtmospheresTopsi_3() throws {
		let result = Pressure.Atmospheres.topsi(1.2)
		XCTAssertEqual(17.6351, result, accuracy: 0.01)
	}

}

final class BarsTests: XCTestCase {
	func testConvertKnownBarsToatmospheres_1() throws {
		let result = Pressure.Bars.toatmospheres(800.0)
		XCTAssertEqual(789.539, result, accuracy: 0.01)
	}

	func testConvertKnownBarsToatmospheres_2() throws {
		let result = Pressure.Bars.toatmospheres(123.0)
		XCTAssertEqual(121.392, result, accuracy: 0.01)
	}

	func testConvertKnownBarsToatmospheres_3() throws {
		let result = Pressure.Bars.toatmospheres(89.0)
		XCTAssertEqual(87.8362, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTopascals_1() throws {
		let result = Pressure.Bars.topascals(0.89)
		XCTAssertEqual(89000.0, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTopascals_2() throws {
		let result = Pressure.Bars.topascals(0.01)
		XCTAssertEqual(1000.0, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTopascals_3() throws {
		let result = Pressure.Bars.topascals(0.123)
		XCTAssertEqual(12300.0, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTotorrs_1() throws {
		let result = Pressure.Bars.totorrs(0.123)
		XCTAssertEqual(92.257587, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTotorrs_2() throws {
		let result = Pressure.Bars.totorrs(2.0)
		XCTAssertEqual(1500.12, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTotorrs_3() throws {
		let result = Pressure.Bars.totorrs(8.9)
		XCTAssertEqual(6675.55, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTopsi_1() throws {
		let result = Pressure.Bars.topsi(8.1)
		XCTAssertEqual(117.481, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTopsi_2() throws {
		let result = Pressure.Bars.topsi(1001.0)
		XCTAssertEqual(14518.29290, result, accuracy: 0.01)
	}

	func testConvertKnownBarsTopsi_3() throws {
		let result = Pressure.Bars.topsi(6.0)
		XCTAssertEqual(87.0226, result, accuracy: 0.01)
	}

}

final class PascalsTests: XCTestCase {
	func testConvertKnownPascalsToatmospheres_1() throws {
		let result = Pressure.Pascals.toatmospheres(90000.0)
		XCTAssertEqual(0.88823094, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsToatmospheres_2() throws {
		let result = Pressure.Pascals.toatmospheres(1234567.0)
		XCTAssertEqual(12.18422897, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsToatmospheres_3() throws {
		let result = Pressure.Pascals.toatmospheres(204060.0)
		XCTAssertEqual(2.01391562, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTobars_1() throws {
		let result = Pressure.Pascals.tobars(10000.0)
		XCTAssertEqual(0.1, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTobars_2() throws {
		let result = Pressure.Pascals.tobars(12345.0)
		XCTAssertEqual(0.12345, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTobars_3() throws {
		let result = Pressure.Pascals.tobars(80000.0)
		XCTAssertEqual(0.8, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTotorrs_1() throws {
		let result = Pressure.Pascals.totorrs(80000.0)
		XCTAssertEqual(600.04935, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTotorrs_2() throws {
		let result = Pressure.Pascals.totorrs(1234.0)
		XCTAssertEqual(9.255761, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTotorrs_3() throws {
		let result = Pressure.Pascals.totorrs(80.0)
		XCTAssertEqual(0.600049, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTopsi_1() throws {
		let result = Pressure.Pascals.topsi(800.0)
		XCTAssertEqual(0.11603, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTopsi_2() throws {
		let result = Pressure.Pascals.topsi(8670.0)
		XCTAssertEqual(1.257477, result, accuracy: 0.01)
	}

	func testConvertKnownPascalsTopsi_3() throws {
		let result = Pressure.Pascals.topsi(1000.0)
		XCTAssertEqual(0.145038, result, accuracy: 0.01)
	}

}

final class PsiTests: XCTestCase {
	func testConvertKnownPsiTobars_1() throws {
		let result = Pressure.Psi.tobars(900.0)
		XCTAssertEqual(62.0528, result, accuracy: 0.01)
	}

	func testConvertKnownPsiTobars_2() throws {
		let result = Pressure.Psi.tobars(134.0)
		XCTAssertEqual(9.23897, result, accuracy: 0.01)
	}

	func testConvertKnownPsiTobars_3() throws {
		let result = Pressure.Psi.tobars(111.2)
		XCTAssertEqual(7.6669701, result, accuracy: 0.01)
	}

	func testConvertKnownPsiTopascals_1() throws {
		let result = Pressure.Psi.topascals(0.9)
		XCTAssertEqual(6205.28, result, accuracy: 0.01)
	}

	func testConvertKnownPsiTopascals_2() throws {
		let result = Pressure.Psi.topascals(0.03)
		XCTAssertEqual(206.8427, result, accuracy: 0.01)
	}

	func testConvertKnownPsiTopascals_3() throws {
		let result = Pressure.Psi.topascals(2.0)
		XCTAssertEqual(13789.5, result, accuracy: 0.01)
	}

	func testConvertKnownPsiToatmospheres_1() throws {
		let result = Pressure.Psi.toatmospheres(2.0)
		XCTAssertEqual(0.136092, result, accuracy: 0.01)
	}

	func testConvertKnownPsiToatmospheres_2() throws {
		let result = Pressure.Psi.toatmospheres(109.0)
		XCTAssertEqual(7.41701, result, accuracy: 0.01)
	}

	func testConvertKnownPsiToatmospheres_3() throws {
		let result = Pressure.Psi.toatmospheres(8.0)
		XCTAssertEqual(0.544368, result, accuracy: 0.01)
	}

	func testConvertKnownPsiTotorrs_1() throws {
		let result = Pressure.Psi.totorrs(6.0)
		XCTAssertEqual(310.29, result, accuracy: 0.01)
	}

	func testConvertKnownPsiTotorrs_2() throws {
		let result = Pressure.Psi.totorrs(3.4)
		XCTAssertEqual(175.831, result, accuracy: 0.01)
	}

	func testConvertKnownPsiTotorrs_3() throws {
		let result = Pressure.Psi.totorrs(0.5)
		XCTAssertEqual(25.8575, result, accuracy: 0.01)
	}

}

final class TorrsTests: XCTestCase {
	func testConvertKnownTorrsTobars_1() throws {
		let result = Pressure.Torrs.tobars(100.0)
		XCTAssertEqual(0.133322, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsTobars_2() throws {
		let result = Pressure.Torrs.tobars(9000.1)
		XCTAssertEqual(11.9991465, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsTobars_3() throws {
		let result = Pressure.Torrs.tobars(1234.0)
		XCTAssertEqual(1.645198, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsTopascals_1() throws {
		let result = Pressure.Torrs.topascals(190.0)
		XCTAssertEqual(25331.2499, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsTopascals_2() throws {
		let result = Pressure.Torrs.topascals(6.5)
		XCTAssertEqual(866.595, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsTopascals_3() throws {
		let result = Pressure.Torrs.topascals(3.4)
		XCTAssertEqual(453.296, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsToatmospheres_1() throws {
		let result = Pressure.Torrs.toatmospheres(5678.0)
		XCTAssertEqual(7.471053, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsToatmospheres_2() throws {
		let result = Pressure.Torrs.toatmospheres(100.0)
		XCTAssertEqual(0.131579, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsToatmospheres_3() throws {
		let result = Pressure.Torrs.toatmospheres(4509.0)
		XCTAssertEqual(5.932895, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsTopsi_1() throws {
		let result = Pressure.Torrs.topsi(4500.0)
		XCTAssertEqual(87.01549, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsTopsi_2() throws {
		let result = Pressure.Torrs.topsi(1234.0)
		XCTAssertEqual(23.86158, result, accuracy: 0.01)
	}

	func testConvertKnownTorrsTopsi_3() throws {
		let result = Pressure.Torrs.topsi(900.0)
		XCTAssertEqual(17.4031, result, accuracy: 0.01)
	}

}

