// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

public final class DataTransferRate {
	@available(*, unavailable) private init() {}

	public final class BitsPerSecond {
		@available(*, unavailable) private init() {}

		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value / 1e+6;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value / 1e+9;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 1e+12;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value / 8000.0;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value / 8e+6;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value / 8e+9;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 8e+12;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value / 1024.0;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value / 1048576.0;
		}
	}

	public final class GigaBitsPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 1e+9;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 1e+6;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value * 125000.0;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value * 125.0;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value / 8.0;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 8000.0;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value * 976562.5;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value * 954.0;
		}
	}

	public final class GigaBytesPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 8e+9;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 8e+6;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value * 8000.0;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value * 8.0;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 125.0;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value * 1e+6;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value * 7812500.0;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value * 7629.39;
		}
	}

	public final class KibibitsPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 1024.0;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 1.024;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value / 976.563;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value / 976562.5;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 976562500.0;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value / 7.812;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value / 7812.5;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value / 7812500.0;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 7812500000.0;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value / 1024.0;
		}
	}

	public final class KiloBitsPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value / 1e+6;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 1e+9;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value / 8.0;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value / 8000.0;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value / 8e+6;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 8e+9;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value / 1.024;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value / 1048.58;
		}
	}

	public final class KiloBytesPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 8000.0;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 8.0;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value / 125.0;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value / 125000.0;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 1.25e+8;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value / 1e+6;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 1e+9;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value * 7.812;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value * 0.00762939;
		}
	}

	public final class MebibitsPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 1048576.0;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 1048.58;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value * 1.04858;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value / 954.0;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 953674.0;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value / 0.00762939;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value / 7.62939;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value / 7629.39;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value * 0.000000131072;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value * 1024.0;
		}
	}

	public final class MegaBitsPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 1e+6;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 1e+6;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value * 125.0;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value / 8.0;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value / 8000.0;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 8e+6;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value * 976.563;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value / 1.04858;
		}
	}

	public final class MegaBytesPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 8e+6;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 8000.0;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value * 8.0;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value / 125.0;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value / 125000.0;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 1e+6;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value * 7812.5;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value * 7.62939;
		}
	}

	public final class TeraBitsPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 1e+12;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 1e+9;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value * 1e+6;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value * 1.25e+8;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value * 125000.0;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value * 125.0;
		}
		public static func toTeraBytesPerSecond(_ value : Double) -> Double {
			return value / 8.0;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value * 976562500.0;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value * 953674.0;
		}
	}

	public final class TeraBytesPerSecond {
		@available(*, unavailable) private init() {}

		public static func toBitsPerSecond(_ value : Double) -> Double {
			return value * 8e+12;
		}
		public static func toKiloBitsPerSecond(_ value : Double) -> Double {
			return value * 8e+9;
		}
		public static func toMegaBitsPerSecond(_ value : Double) -> Double {
			return value * 8e+6;
		}
		public static func toGigaBitsPerSecond(_ value : Double) -> Double {
			return value * 8000.0;
		}
		public static func toTeraBitsPerSecond(_ value : Double) -> Double {
			return value * 8.0;
		}
		public static func toKiloBytesPerSecond(_ value : Double) -> Double {
			return value * 1e+9;
		}
		public static func toMegaBytesPerSecond(_ value : Double) -> Double {
			return value * 1e+6;
		}
		public static func toGigaBytesPerSecond(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toKibibitsPerSecond(_ value : Double) -> Double {
			return value * 7812500000.0;
		}
		public static func toMebibitsPerSecond(_ value : Double) -> Double {
			return value / 0.000000131072;
		}
	}
}
