// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

public final class Energy {
	@available(*, unavailable) private init() {}

	public final class Btu {
		@available(*, unavailable) private init() {}

		public static func toKilojoules(_ value : Double) -> Double {
			return value * 1.0550559;
		}
		public static func toKilocalories(_ value : Double) -> Double {
			return value / 3.9673727240424;
		}
		public static func toJoules(_ value : Double) -> Double {
			return value * 1055.06;
		}
		public static func toCalories(_ value : Double) -> Double {
			return value * 252.164;
		}
		public static func toUSTherms(_ value : Double) -> Double {
			return value / 99976.12448781215;
		}
		public static func toWattHours(_ value : Double) -> Double {
			return value * 0.293071;
		}
		public static func toKilowattHours(_ value : Double) -> Double {
			return value / 3412.14;
		}
		public static func toFootPounds(_ value : Double) -> Double {
			return value * 778.169;
		}
	}

	public final class Calories {
		@available(*, unavailable) private init() {}

		public static func toKilojoules(_ value : Double) -> Double {
			return value / 239.0057;
		}
		public static func toKilocalories(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toJoules(_ value : Double) -> Double {
			return value * 4.184;
		}
		public static func toBtu(_ value : Double) -> Double {
			return value / 252.164;
		}
		public static func toUSTherms(_ value : Double) -> Double {
			return value / 25210420.0;
		}
		public static func toWattHours(_ value : Double) -> Double {
			return value * 0.00116222;
		}
		public static func toKilowattHours(_ value : Double) -> Double {
			return value / 860421.0;
		}
		public static func toFootPounds(_ value : Double) -> Double {
			return value * 3.08596;
		}
	}

	public final class ElectronVolts {
		@available(*, unavailable) private init() {}

	}

	public final class FootPounds {
		@available(*, unavailable) private init() {}

		public static func toKilojoules(_ value : Double) -> Double {
			return value / 737.562;
		}
		public static func toKilocalories(_ value : Double) -> Double {
			return value / 3085.96;
		}
		public static func toJoules(_ value : Double) -> Double {
			return value * 1.35582;
		}
		public static func toBtu(_ value : Double) -> Double {
			return value / 778.169;
		}
		public static func toCalories(_ value : Double) -> Double {
			return value / 3.08596;
		}
		public static func toUSTherms(_ value : Double) -> Double {
			return value / 77816937.099186;
		}
		public static func toWattHours(_ value : Double) -> Double {
			return value / 2655.22;
		}
		public static func toKilowattHours(_ value : Double) -> Double {
			return value * 0.00000037662;
		}
	}

	public final class Joules {
		@available(*, unavailable) private init() {}

		public static func toKilojoules(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toKilocalories(_ value : Double) -> Double {
			return value / 4184.0;
		}
		public static func toBtu(_ value : Double) -> Double {
			return value / 1055.06;
		}
		public static func toCalories(_ value : Double) -> Double {
			return value / 4.184;
		}
		public static func toUSTherms(_ value : Double) -> Double {
			return value / 105480400.0;
		}
		public static func toWattHours(_ value : Double) -> Double {
			return value / 3600.0;
		}
		public static func toKilowattHours(_ value : Double) -> Double {
			return value / 3.6e+6;
		}
		public static func toFootPounds(_ value : Double) -> Double {
			return value / 1.35582;
		}
	}

	public final class Kilocalories {
		@available(*, unavailable) private init() {}

		public static func toKilojoules(_ value : Double) -> Double {
			return value * 4.184;
		}
		public static func toJoules(_ value : Double) -> Double {
			return value * 4184.0;
		}
		public static func toBtu(_ value : Double) -> Double {
			return value * 3.9673727240424;
		}
		public static func toCalories(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toUSTherms(_ value : Double) -> Double {
			return value / 25210.4;
		}
		public static func toWattHours(_ value : Double) -> Double {
			return value * 1.16222;
		}
		public static func toKilowattHours(_ value : Double) -> Double {
			return value / 860.421;
		}
		public static func toFootPounds(_ value : Double) -> Double {
			return value * 3085.96;
		}
	}

	public final class Kilojoules {
		@available(*, unavailable) private init() {}

		public static func toKilocalories(_ value : Double) -> Double {
			return value / 4.184;
		}
		public static func toJoules(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toBtu(_ value : Double) -> Double {
			return value / 1.0550559;
		}
		public static func toCalories(_ value : Double) -> Double {
			return value * 239.0057;
		}
		public static func toUSTherms(_ value : Double) -> Double {
			return value / 105480.04;
		}
		public static func toWattHours(_ value : Double) -> Double {
			return value / 3.6;
		}
		public static func toKilowattHours(_ value : Double) -> Double {
			return value / 3600.0;
		}
		public static func toFootPounds(_ value : Double) -> Double {
			return value * 737.562;
		}
	}

	public final class KilowattHours {
		@available(*, unavailable) private init() {}

		public static func toKilojoules(_ value : Double) -> Double {
			return value * 3600.0;
		}
		public static func toKilocalories(_ value : Double) -> Double {
			return value * 860.421;
		}
		public static func toJoules(_ value : Double) -> Double {
			return value * 3.6e+6;
		}
		public static func toBtu(_ value : Double) -> Double {
			return value * 3412.14;
		}
		public static func toCalories(_ value : Double) -> Double {
			return value * 860421.0;
		}
		public static func toUSTherms(_ value : Double) -> Double {
			return value / 29.3001;
		}
		public static func toWattHours(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toFootPounds(_ value : Double) -> Double {
			return value / 0.00000037662;
		}
	}

	public final class USTherms {
		@available(*, unavailable) private init() {}

		public static func toKilojoules(_ value : Double) -> Double {
			return value * 105480.04;
		}
		public static func toKilocalories(_ value : Double) -> Double {
			return value * 25210.4;
		}
		public static func toJoules(_ value : Double) -> Double {
			return value * 105480400.0;
		}
		public static func toBtu(_ value : Double) -> Double {
			return value * 99976.12448781215;
		}
		public static func toCalories(_ value : Double) -> Double {
			return value * 25210420.0;
		}
		public static func toWattHours(_ value : Double) -> Double {
			return value * 29300.1;
		}
		public static func toKilowattHours(_ value : Double) -> Double {
			return value * 29.3001;
		}
		public static func toFootPounds(_ value : Double) -> Double {
			return value * 77816937.099186;
		}
	}

	public final class WattHours {
		@available(*, unavailable) private init() {}

		public static func toKilojoules(_ value : Double) -> Double {
			return value * 3.6;
		}
		public static func toKilocalories(_ value : Double) -> Double {
			return value / 1.16222;
		}
		public static func toJoules(_ value : Double) -> Double {
			return value * 3600.0;
		}
		public static func toBtu(_ value : Double) -> Double {
			return value / 0.293071;
		}
		public static func toCalories(_ value : Double) -> Double {
			return value / 0.00116222;
		}
		public static func toUSTherms(_ value : Double) -> Double {
			return value / 29300.1;
		}
		public static func toKilowattHours(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toFootPounds(_ value : Double) -> Double {
			return value * 2655.22;
		}
	}
}
