// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

public final class Frequency {
	@available(*, unavailable) private init() {}

	public final class Gigahertz {
		@available(*, unavailable) private init() {}

		public static func toHertz(_ value : Double) -> Double {
			return value * 1e+9;
		}
		public static func toKilohertz(_ value : Double) -> Double {
			return value * 1e+6;
		}
		public static func toMegahertz(_ value : Double) -> Double {
			return value * 1000.0;
		}
	}

	public final class Hertz {
		@available(*, unavailable) private init() {}

		public static func toKilohertz(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toMegahertz(_ value : Double) -> Double {
			return value / 1e+6;
		}
		public static func toGigahertz(_ value : Double) -> Double {
			return value / 1e+9;
		}
	}

	public final class Kilohertz {
		@available(*, unavailable) private init() {}

		public static func toHertz(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toMegahertz(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toGigahertz(_ value : Double) -> Double {
			return value / 1e+6;
		}
	}

	public final class Megahertz {
		@available(*, unavailable) private init() {}

		public static func toHertz(_ value : Double) -> Double {
			return value * 1e+6;
		}
		public static func toKilohertz(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toGigahertz(_ value : Double) -> Double {
			return value / 1000.0;
		}
	}
}
