// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import PackageDescription

let package = Package(
	name: "Swift.Units",
	products: [
		.library(
			name: "Swift.Units",
			targets: ["Swift.Units"]),
	],
	dependencies: [
	],
	targets: [
		.target(
			name: "Swift.Units",
			dependencies: []),
		.testTarget(
			name: "Swift.UnitsTests",
			dependencies: ["Swift.Units"]),
	]
)
