// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

public final class Temperature {
	@available(*, unavailable) private init() {}

	public final class Celsius {
		@available(*, unavailable) private init() {}

		public static func toFahrenheit(_ value : Double) -> Double {
			return value * 1.8 + 32.0;
		}
		public static func toKelvin(_ value : Double) -> Double {
			return value + 273.15;
		}
		public static func toRankine(_ value : Double) -> Double {
			return value * 9.0/5.0 + 491.67;
		}
		public static func toReaumur(_ value : Double) -> Double {
			return value / 1.25;
		}
	}

	public final class Fahrenheit {
		@available(*, unavailable) private init() {}

		public static func toCelsius(_ value : Double) -> Double {
			return ((value - 32.0) * 5.0) / 9.0;
		}
		public static func toKelvin(_ value : Double) -> Double {
			return (((value - 32.0) * 5.0) / 9.0) + 273.15;
		}
		public static func toRankine(_ value : Double) -> Double {
			return value + 459.67;
		}
		public static func toReaumur(_ value : Double) -> Double {
			return (value - 32.0) / 2.25;
		}
	}

	public final class Kelvin {
		@available(*, unavailable) private init() {}

		public static func toCelsius(_ value : Double) -> Double {
			return value - 273.15;
		}
		public static func toFahrenheit(_ value : Double) -> Double {
			return ((value - 273.15) * 1.8) + 32.0;
		}
		public static func toRankine(_ value : Double) -> Double {
			return value * 1.8;
		}
		public static func toReaumur(_ value : Double) -> Double {
			return (value - 273.15) / 1.25;
		}
	}

	public final class Rankine {
		@available(*, unavailable) private init() {}

		public static func toCelsius(_ value : Double) -> Double {
			return (value - 491.67) * 5.0/9.0;
		}
		public static func toFahrenheit(_ value : Double) -> Double {
			return value - 459.67;
		}
		public static func toKelvin(_ value : Double) -> Double {
			return value / 1.8;
		}
		public static func toReaumur(_ value : Double) -> Double {
			return (value - 491.67) / 2.25;
		}
	}

	public final class Reaumur {
		@available(*, unavailable) private init() {}

		public static func toKelvin(_ value : Double) -> Double {
			return value * 1.25 + 273.15;
		}
		public static func toCelsius(_ value : Double) -> Double {
			return value * 1.25;
		}
		public static func toFahrenheit(_ value : Double) -> Double {
			return value * 2.25 + 32.0;
		}
		public static func toRankine(_ value : Double) -> Double {
			return value * 2.25 + 491.67;
		}
	}
}
