// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

public final class Volume {
	@available(*, unavailable) private init() {}

	public final class FluidOunces {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 28.413074243749994496;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.028413074243749994496;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000028413074243749994;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 4.8;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 1.6;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value / 40.0;
		}
		public static func toPints(_ value : Double) -> Double {
			return value / 20.0;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value / 160.0;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 0.1734737167638313984;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 0.52042115029149417472;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 33.306953618655629312;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 16.653476809327814656;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 133.22781447462252544;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 1.0408423005829883904;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 8.3267384046639071232;
		}
	}

	public final class Gallons {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 4546.091879;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 4.546091879;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.0045460918799;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 768.0;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 256.0;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value * 4.0;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 8.0;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 160.0;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 0.00108421072977394606;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 0.003252632189321838592;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 0.20816846011659767808;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 0.10408423005829883904;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 0.83267384046639071232;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 0.006505264378643677184;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 0.052042115029149417472;
		}
	}

	public final class Kilolitres {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 1000000.0;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value / 0.000005919390467447916;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value / 0.000017758171402343747;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value / 0.00113652296975;
		}
		public static func toPints(_ value : Double) -> Double {
			return value / 0.000568261484874999889;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value / 0.0045460918799;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value / 0.0000284130742437499946;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 0.000004928921593749999;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 0.000014786764781249998;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 0.000946352945999999959;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 0.000473176472999999979;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 0.003785411784;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 0.0000295735296;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 0.000236588236499999989;
		}
	}

	public final class Litres {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 1000.0;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value / 0.005919390467447916134;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value / 0.017758171402343747584;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value / 1.13652296975;
		}
		public static func toPints(_ value : Double) -> Double {
			return value / 0.56826148487499988992;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value / 4.546091879;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value / 0.028413074243749994496;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 0.004928921593749999616;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 0.014786764781249998848;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 0.94635294599999995904;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 0.47317647299999997952;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 3.785411784;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 0.029573529562499997696;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 0.23658823649999998976;
		}
	}

	public final class Millilitres {
		@available(*, unavailable) private init() {}

		public static func toLitres(_ value : Double) -> Double {
			return value / 1000.0;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value / 1000000.0;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value / 5.9193904674479161344;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value / 17.758171402343747584;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value / 1136.52296975;
		}
		public static func toPints(_ value : Double) -> Double {
			return value / 568.26148487499988992;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value / 4546.091879;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value / 28.413074243749994496;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 4.928921593749999616;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 14.786764781249998848;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 946.35294599999995904;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 473.17647299999997952;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 3785.411784;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 29.573529562499997696;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 236.58823649999998976;
		}
	}

	public final class Pints {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 568.26148487499988992;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.56826148487499988992;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000568261484874999889;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 96.0;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 32.0;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value  / 2.0;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value / 8.0;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 20.0;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 0.008673685838191568486;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 0.026021057514574708736;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 1.6653476809327814656;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 0.83267384046639071232;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 6.6613907237311258624;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 0.052042115029149417472;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 0.41633692023319535616;
		}
	}

	public final class Quarts {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 1136.52296975;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 1.13652296975;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.00113652296975;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 192.0;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 64.0;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 2.0;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value / 4.0;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 40.0;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 0.004336842919095784243;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 0.013010528757287354368;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 0.83267384046639071232;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 0.41633692023319535616;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 3.3306953618655629312;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 0.026021057514574708736;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 0.20816846011659767808;
		}
	}

	public final class Tablespoons {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 17.758171402343747584;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.017758171402343747584;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000017758171402343747;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 3.0;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value / 64.0;
		}
		public static func toPints(_ value : Double) -> Double {
			return value / 32.0;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value / 256.0;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value / 1.6;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 0.27755794682213023744;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 0.83267384046639071232;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 53.291125789849001984;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 26.645562894924500992;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 213.16450315939602432;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 1.6653476809327814656;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 13.322781447462250496;
		}
	}

	public final class Teaspoons {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 5.9193904674479161344;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.005919390467447916134;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000005919390467447916;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value / 3.0;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value / 192.0;
		}
		public static func toPints(_ value : Double) -> Double {
			return value / 96.0;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value / 768.0;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value / 4.8;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value / 0.83267384046639071232;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 2.4980215213991718912;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 159.87337736954701824;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 79.936688684773507072;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 639.49350947818807296;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 4.9960430427983437824;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 39.968344342386753536;
		}
	}

	public final class USCups {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 236.58823649999998976;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.23658823649999998976;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000236588236499999989;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 39.968344342386753536;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 13.322781447462250496;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value * 0.20816846011659767808;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 0.41633692023319535616;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value * 0.052042115029149417472;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 8.3267384046639071232;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value * 48.0;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value * 16.0;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 4.0;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 2.0;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 16.0;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value * 8.0;
		}
	}

	public final class USFluidOunces {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 29.573529562499997696;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.029573529562499997696;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.0000295735296;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 4.9960430427983437824;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 1.6653476809327814656;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value * 0.026021057514574708736;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 0.052042115029149417472;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value * 0.006505264378643677184;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 1.0408423005829883904;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value * 6.0;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value * 2.0;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 32.0;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 16.0;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 128.0;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 8.0;
		}
	}

	public final class USGallons {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 3785.411784;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 3.785411784;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.003785411784;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 639.49350947818807296;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 213.16450315939602432;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value * 3.3306953618655629312;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 6.6613907237311258624;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value * 0.83267384046639071232;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 133.22781447462252544;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value * 768.0;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value * 256.0;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value * 4.0;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value * 8.0;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value * 128.0;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value * 16.0;
		}
	}

	public final class USPints {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 473.17647299999997952;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.47317647299999997952;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000473176472999999979;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 79.936688684773507072;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 26.645562894924500992;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value * 0.41633692023319535616;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 0.83267384046639071232;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value * 0.10408423005829883904;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 16.653476809327814656;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value * 96.0;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value * 32.0;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 2.0;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 8.0;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value * 16.0;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value * 2.0;
		}
	}

	public final class USQuarts {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 946.35294599999995904;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.94635294599999995904;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000946352945999999959;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 159.87337736954701824;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 53.291125789849001984;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value * 0.83267384046639071232;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 1.6653476809327814656;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value * 0.20816846011659767808;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 33.306953618655629312;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value * 192.0;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value * 64.0;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value * 2.0;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 4.0;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value * 32.0;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value * 4.0;
		}
	}

	public final class USTablespoons {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 14.786764781249998848;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.014786764781249998848;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000014786764781249998;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 2.4980215213991718912;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 0.83267384046639071232;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value * 0.013010528757287354368;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 0.026021057514574708736;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value * 0.003252632189321838592;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 0.52042115029149417472;
		}
		public static func toUSTeaspoons(_ value : Double) -> Double {
			return value * 3.0;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 64.0;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 32.0;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 256.0;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 2.0;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 16.0;
		}
	}

	public final class USTeaspoons {
		@available(*, unavailable) private init() {}

		public static func toMillilitres(_ value : Double) -> Double {
			return value * 4.928921593749999616;
		}
		public static func toLitres(_ value : Double) -> Double {
			return value * 0.004928921593749999616;
		}
		public static func toKilolitres(_ value : Double) -> Double {
			return value * 0.000004928921593749999;
		}
		public static func toTeaspoons(_ value : Double) -> Double {
			return value * 0.83267384046639071232;
		}
		public static func toTablespoons(_ value : Double) -> Double {
			return value * 0.27755794682213023744;
		}
		public static func toQuarts(_ value : Double) -> Double {
			return value * 0.004336842919095784243;
		}
		public static func toPints(_ value : Double) -> Double {
			return value * 0.008673685838191568486;
		}
		public static func toGallons(_ value : Double) -> Double {
			return value * 0.00108421072977394606;
		}
		public static func toFluidOunces(_ value : Double) -> Double {
			return value * 0.1734737167638313984;
		}
		public static func toUSTablespoons(_ value : Double) -> Double {
			return value / 3.0;
		}
		public static func toUSQuarts(_ value : Double) -> Double {
			return value / 192.0;
		}
		public static func toUSPints(_ value : Double) -> Double {
			return value / 96.0;
		}
		public static func toUSGallons(_ value : Double) -> Double {
			return value / 768.0;
		}
		public static func toUSFluidOunces(_ value : Double) -> Double {
			return value / 6.0;
		}
		public static func toUSCups(_ value : Double) -> Double {
			return value / 48.0;
		}
	}
}
